version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
