version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    volumes:
      - /Users/yuliaantsybor/dofd-05-yuliia-antsybor/:/app

  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - /Users/yuliaantsybor/dofd-05-yuliia-antsybor/:/app
