- name: Use custom node version
uses: actions/setup-node@v3
with:
node-version: 16
- name: Checkout frontend from develop branch
uses: actions/checkout@v3
with:
repository: ita-social-projects/TeachUAClient
ref: develop
- name: Install dependencies
run: "npm install --legacy-peer-deps"
